### ISSUE TITLE
enable client to specify initial state of panel (open or closed)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/embed-lib#39]
initial state of the panel should be a constructor arg

**Comment by balmas** [comment]
I think this is done now.  @kirlat can you confirm?

**Comment by kirlat** [comment]
I think it does not work this way currently, since we've implemented the requirement to have either the toolbar or the panel open. As we always show a toolbar on the activation, the panel is thus always closed. 

How should it behave now? If panel's initial state is set to `true`, shall we open the panel and hide the toolbar on activation?

**Comment by balmas** [comment]
Ah, I think maybe the new toolbar behavior obviates the need for this. Let's close it until/unless we get a request for it.
